package com.aurora.pos.sri.autorizacion;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.0.8.5
//
// Created by Quasar Development 
//
//---------------------------------------------------


import org.ksoap2.serialization.*;

import java.util.Hashtable;

public class respuestaComprobante extends AttributeContainer implements KvmSerializable
{

    
    public String claveAccesoConsultada;
    
    public String numeroComprobantes;
    
    public respuestaComprobante_autorizaciones autorizaciones;

    public respuestaComprobante ()
    {
    }

    public respuestaComprobante (Object paramObj,ExtendedSoapSerializationEnvelope __envelope)
    {

	    if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;


        if(inObj instanceof SoapObject)
        {
            SoapObject soapObject=(SoapObject)inObj;
            int size = soapObject.getPropertyCount();
            for (int i0=0;i0< size;i0++)
            {
                //if you have compilation error here, please use a ksoap2.jar and ExKsoap2.jar from libs folder (in the generated zip file)
                PropertyInfo info=soapObject.getPropertyInfo(i0);
                Object obj = info.getValue();
                if (info.name.equals("claveAccesoConsultada"))
                {
                    if(obj!=null)
                    {

                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.claveAccesoConsultada = j.toString();
                            }
                        }
                        else if (obj instanceof String){
                            this.claveAccesoConsultada = (String)obj;
                        }
                    }
                    continue;
                }
                if (info.name.equals("numeroComprobantes"))
                {
                    if(obj!=null)
                    {

                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.numeroComprobantes = j.toString();
                            }
                        }
                        else if (obj instanceof String){
                            this.numeroComprobantes = (String)obj;
                        }
                    }
                    continue;
                }
                if (info.name.equals("autorizaciones"))
                {
                    if(obj!=null)
                    {
                        Object j = obj;
                        this.autorizaciones = new respuestaComprobante_autorizaciones(j,__envelope);
                    }
                    continue;
                }

            }

        }



    }

    @Override
    public Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==0)
        {
            return this.claveAccesoConsultada!=null?this.claveAccesoConsultada:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==1)
        {
            return this.numeroComprobantes!=null?this.numeroComprobantes:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==2)
        {
            return this.autorizaciones!=null?this.autorizaciones:SoapPrimitive.NullSkip;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 3;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
        if(propertyIndex==0)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "claveAccesoConsultada";
            info.namespace= "";
        }
        if(propertyIndex==1)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "numeroComprobantes";
            info.namespace= "";
        }
        if(propertyIndex==2)
        {
            info.type = PropertyInfo.VECTOR_CLASS;
            info.name = "autorizaciones";
            info.namespace= "";
        }
    }

    @Override
    public void setProperty(int arg0, Object arg1)
    {
    }

    
}

